name: 🚀 Deploy Astro site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOSTINGER_IP }}
          username: ${{ vars.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
          port: ${{ vars.HOSTINGER_SSH_PORT }}
          source: "dist/*"
          target: domains/javlintor.com/public_html
